services:
  - type: web
    name: online-quiz-system-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_ZYvghJSB7j2u@ep-plain-forest-ano7syja.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
